// Regenerates js/data.js from the GeoJSON files in data/, so the page works
// when opened directly from disk (browsers block fetch() on file:// pages).
// scripts/update_offline_data.py does this too after downloading new data.
// Run after hand-editing anything in data/:   node scripts/build-data.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const path = (f) => new URL(`../data/${f}`, import.meta.url);
const read = (f) => JSON.parse(readFileSync(path(f), 'utf8'));
const data = { boundary: read('kingston-boundary.geojson') };
if (existsSync(path('article4-official.geojson'))) data.offlineA4 = read('article4-official.geojson');
if (existsSync(path('article4-legacy-2022.geojson'))) data.legacyA4 = read('article4-legacy-2022.geojson');
const out = '// Generated by scripts/update_offline_data.py (or scripts/build-data.mjs) from data/*.geojson. Do not edit by hand.\n' +
  `window.A4_DATA = ${JSON.stringify(data)};\n`;
writeFileSync(new URL('../js/data.js', import.meta.url), out);
console.log(`js/data.js written (${(out.length / 1024).toFixed(0)} KB)`);
