// Regenerates js/data.js from the GeoJSON files in data/, so the page works
// when opened directly from disk (browsers block fetch() on file:// pages).
// Run after changing anything in data/:   node scripts/build-data.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const read = (f) => JSON.parse(readFileSync(new URL(`../data/${f}`, import.meta.url)));
const data = {
  boundary: read('kingston-boundary.geojson'),
  legacyA4: read('article4-legacy-2022.geojson'),
};
const out = `// Generated by scripts/build-data.mjs from data/*.geojson. Do not edit by hand.\nwindow.A4_DATA = ${JSON.stringify(data)};\n`;
writeFileSync(new URL('../js/data.js', import.meta.url), out);
console.log(`js/data.js written (${(out.length / 1024).toFixed(1)} KB)`);
